### ISSUE TITLE
Spoofing Preferences: Pretend to be an xbox 360 controller 

### ISSUE THREAD

**Issue by Jakedjoe** [360Controller/360Controller#663]
Small but annoying issue:

under Spoofing Preferences, Pretend to be an xbox 360 controller toggle button is not saving the preference. My third party PowerA controller works fine when this preference is toggled. However, when I close the setting menu the preference does not save. So I need to launch the menu every time I want to play, toggle the button, and keep it open; or else the mapping for the game is completely off.

**Comment by FranticRain** [comment]
This should have been fixed in 0.16.6. What version are you using?

**Comment by Jakedjoe** [comment]
version 0.16.6

**Comment by FranticRain** [comment]
This should be fixed in the latest release.

**Comment by wbbradley** [comment]
This issue (or perhaps a variant of it) still persists. When I close the lid on my MacBook Pro, and reopen it, the spoofing preference seems to relapse to Off, when I had set it to On. Is this a known issue?
